gui:
  nerdFontsVersion: "3"

customCommands:
  - key: 'p'
    context: 'global'
    command: 'git pull --recurse-submodules'
    loadingText: 'Pulling with submodules'
    output: 'log'
  - key: '<c-p>'
    context: 'global'
    command: 'git pull'
    loadingText: 'Pulling remote repo'
    output: 'log'