#!/bin/bash

set -e
# set -x
set -o pipefail

function  createLink(){

  echo -e "Testing [$1]"

#  if [[ -e ${1} || -L ${1} ]] ; then
#    echo -e "  Already exists [$1]"
#  else
    ln -s -f "$2" "$1"
    echo -e "  Symlink [$1] created"
#  fi
}

# if  [[ ! -d "$HOME/.config/alacritty" ]]; then
#   mkdir "$HOME/.config/alacritty"
# fi

createLink "${HOME}/.config/alacritty"	"${PWD}/alacritty"

echo -e ""
echo "Symlink Completed"
