theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
completion-replace = true
cursorline = true
scrolloff = 6
mouse = true
middle-click-paste = true
scroll-lines = 3
shell = ["zsh", "-c"]
cursorcolumn = false
gutters = ["diagnostics", "spacer", "diff", "line-numbers", "spacer", "spacer"]
auto-completion = true
auto-format = true
auto-save = true
idle-timeout = 60
completion-trigger-len = 2
auto-info = true
true-color = true
rulers = []
bufferline = "multiple"
color-modes = true
auto-pairs = true

[editor.statusline]
left = [
  "mode",
  "spacer",
  "version-control",
  "spacer",
  "separator",
  "file-name",
  "file-modification-indicator",
]

center = []

right = [
  "spinner",
  "spacer",
  "workspace-diagnostics",
  "separator",
  "spacer",
  "diagnostics",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]

separator = "\uE0B3"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.search]
smart-case = false

[editor.file-picker]
hidden = false
git-global = false # show files hidden by git globally
# max-depth = 20

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = true
auto-signature-help = true
display-signature-help-docs = true

[keys.normal]
D = "kill_to_line_end"
"C-d" = ["half_page_down", "goto_window_center"]
"C-u" = ["half_page_up", "goto_window_center"]
"tab" = ":bn"
"S-tab" = ":bp"
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
# "%" = "match_brackets"

[keys.insert]
C-space = "completion"
