# theme = "tokyonight"
theme = "catppuccin_frappe"

[editor]
line-number = "relative"
# bufferline = "multiple"
scrolloff = 6
mouse = true
middle-click-paste = true
scroll-lines = 3
shell = [ "zsh", "-c" ]
cursorline = true
cursorcolumn = false
gutters = [ "diff", "line-numbers", "spacer", ]
auto-completion = true
auto-format = true
auto-save = false
idle-timeout = 0
completion-trigger-len = 2
auto-info = true
true-color = true
rulers = []
bufferline = "always"
color-modes = true
auto-pairs = true

[editor.statusline]
left = [ "mode", "file-name", "separator", "spacer", "diagnostics", ]
center = []
right = [
  "position", "separator",  "spacer", "position-percentage", "spacer", "separator", 
  "total-line-numbers", "separator",  "file-line-ending", "separator",  "file-type", ]
separator = "\uE0B3"
mode.normal = "NORMAL"
mode.select = "SELECT"
mode.insert = "INSERT"

[editor.soft-wrap]
enable = true
wrap-indicator = ""
max-indent-retain = 0
wrap-at-text-width = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.search]
smart-case = false

[editor.file-picker]
hidden = false
git-global = false # show files hidden by git globally
max-depth = 20

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = true
auto-signature-help = true

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽" 
skip-levels = 1

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-o = ":open ~/.config/helix/config.toml" # Maps the Control-o to opening of the helix config file
"C-S-esc" = "extend_line" # Maps Control-Shift-Escape to extend_line
g = { a = "code_action" } # Maps `ga` to show possible code actions
"ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode
"tab" = ":bn"
"S-tab" = ":bp"
"$" = [ "goto_line_end", ]
"^" = [ "goto_first_nonwhitespace", ]
"0" = [ "goto_line_start", ]
"G" = [ "goto_last_line", ]
"M" = [ "goto_window_center", ]

[keys.normal."+"]
m = ":run-shell-command make"
c = ":run-shell-command cargo build"
t = ":run-shell-command cargo check"
r = ":run-shell-command cargo build --release"
i = ":run-shell-command cargo install --path ."
