# theme = "tokyonight"
theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
auto-save = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.search]
smart-case = false

[editor.file-picker]
hidden = false
git-global = false # show files hidden by git globally
max-depth = 20

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = true
auto-signature-help = true

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1


[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-o = ":open ~/.config/helix/config.toml" # Maps the Control-o to opening of the helix config file
"C-S-esc" = "extend_line" # Maps Control-Shift-Escape to extend_line
g = { a = "code_action" } # Maps `ga` to show possible code actions
"ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode
"tab" = ":bn"
"S-tab" = ":bp"