use-grammars = { only = [ "rust", "dockerfile", "python", "go" ] }

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
check = { command = "clippy", features = "all" }
diagnostics = { experimental = { enable = true } }
hover = { actions = { enable = true } }
typing = { autoClosingAngleBrackets = { enable = true } }
cargo = { buildScripts = { enable = true }, features = "all" }
procMacro = { enable = true }

[language-server.rust-analyzer.config.inlayHints]
# lifetimeElisionHints = { enable = false, useParameterNames = false }
# typeHints = { hideNamedConstructor = true, hideClosureInitialization = true }
bindingModeHints.enable = false
closingBraceHints.minLines = 10
closureReturnTypeHints.enable = "with_block"
discriminantHints.enable = "fieldless"
lifetimeElisionHints = { enable = false, useParameterNames = false }
renderColons = false
typeHints = { hideNamedConstructor = true, hideClosureInitialization = true }
parameterHints = { enable = false }
chainingHints = { enable = false }

[language-server.gopls]
command = "gopls"

[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
auto-format = true
comment-token = "//"
language-servers = ["rust-analyzer"]
indent = { tab-width = 2, unit = "  " }

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

# [language.debugger]
# name = "lldb-vscode"
# transport = "stdio"
# command = "lldb-vscode"

# https://github.com/helix-editor/helix/wiki/Debugger-Configurations#configure-debuggers

[language.debugger]
command = "codelldb"
name = "codelldb"
port-arg = "--port {}"
transport = "tcp"

[[language.debugger.templates]]
name = "binary"
request = "launch"

[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"

[language.debugger.templates.args]
program = "{0}"
runInTerminal = true

[[grammar]]
name = "rust"
source = { git = "https://github.com/tree-sitter/tree-sitter-rust", rev = "0431a2c60828731f27491ee9fdefe25e250ce9c9" }

[[language]]
name = "toml"
scope = "source.toml"
injection-regex = "toml"
file-types = ["toml", "poetry.lock", "Cargo.lock"]
comment-token = "#"
language-servers = ["taplo"]
indent = { tab-width = 2, unit = "  " }
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "toml"] }

[[grammar]]
name = "toml"
source = { git = "https://github.com/ikatyang/tree-sitter-toml", rev = "7cff70bbcbbc62001b465603ca1ea88edd668704" }

[language-server.gopls.config.hints]
assignVariableTypes = true
compositeLiteralFields = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

[[language]]
name = "go"
auto-format = true
formatter = { command = "gofumpt" }
indent = { tab-width = 2, unit = "  " }
# config = { analyses = { "unusedparams" = true }, staticcheck = true }

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

[language-server.golangci-lint-lsp.config]
command = [
  "golangci-lint",
  "run",
  "--out-format",
  "json",
  "--issues-exit-code=1",
]

[[grammar]]
name = "go"
source = { git = "https://github.com/tree-sitter/tree-sitter-go", rev = "64457ea6b73ef5422ed1687178d4545c3e91334a" }

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "yaml"] }

[[language]]
name = "json"
auto-format = true
formatter = { command = 'dprint', args = ["fmt", "--stdin", "json"] }

[[language]]
name = "markdown"
scope = "source.md"
injection-regex = "md|markdown"
file-types = [
  "md",
  "markdown",
  "PULLREQ_EDITMSG",
  "mkd",
  "mdwn",
  "mdown",
  "markdn",
  "mdtxt",
  "mdtext",
  "workbook",
]
roots = [".marksman.toml"]
language-servers = ["marksman"]
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "markdown"
source = { git = "https://github.com/MDeiml/tree-sitter-markdown", rev = "aaf76797aa8ecd9a5e78e0ec3681941de6c945ee", subpath = "tree-sitter-markdown" }

[[language]]
name = "markdown.inline"
scope = "source.markdown.inline"
injection-regex = "markdown\\.inline"
file-types = []
grammar = "markdown_inline"

[[grammar]]
name = "markdown_inline"
source = { git = "https://github.com/MDeiml/tree-sitter-markdown", rev = "aaf76797aa8ecd9a5e78e0ec3681941de6c945ee", subpath = "tree-sitter-markdown-inline" }

[[language]]
name = "yaml"
scope = "source.yaml"
file-types = ["yml", "yaml"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
language-servers = ["yaml-language-server", "ansible-language-server"]
injection-regex = "yml|yaml"

[[grammar]]
name = "yaml"
source = { git = "https://github.com/ikatyang/tree-sitter-yaml", rev = "0e36bed171768908f331ff7dff9d956bae016efb" }
