use-grammars = { only = [ "rust", "go", "toml", "sql", "dockerfile", "python" ] }

[[language]]
name = "rust"
auto-format = true
indent = { tab-width = 2, unit = "  " }

[language.config]
cargo = { buildScripts = { enable = true }, features = "all" }
procMacro = { enable = true }

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false
check = { command = "clippy", features = "all" }
diagnostics = { experimental = { enable = true } }
hover = { actions = { enable = true } }
typing = { autoClosingAngleBrackets = { enable = true } }
cargo = { allFeatures = true }
procMacro = { enable = true }

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
roots = ["go.mod"]
comment-token = "//"
language-server = { command = "gopls" }
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "toml"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "toml"]}
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "yaml"] }
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "json"
auto-format = true
formatter = { command = 'dprint', args = ["fmt", "--stdin", "json"] }
indent = { tab-width = 2, unit = "  " }
